### ISSUE TITLE
Split driver and plugin into submodules?

### ISSUE THREAD

**Issue by jwlodek** [ess-dmsc/ad-kafka-interface#8]
Would it be possible to split the driver and plugin repositories into separate repositories that are then referenced in this repository as submodules? We are interested in trying these tools, and we currently are using an automated build system for areaDetector that expects AD Drivers and plugins cloned from github to be able to be placed in `$(EPICS_MODULES)/areaDetector` during cloning, and currently, this is not possible, as the appropriate directory needs to be copied.

I could work around this and add some customized logic to handle this, but it would be simpler if they were accessible as their own individual repositories.

**Comment by SkyToGround** [comment]
Well, in my opinion, git submodules suck and should be avoided at all cost. I am not against splitting this repo into two however. Feel free to remind me if I have not done this within the next few weeks.

**Comment by SkyToGround** [comment]
I have *finally* spent some time doing this. At least splitting the plugin part from the this repo. It is still a work in progress as I am fixing a bunch of design issues at the same time but you can find the plugin repository [here](https://github.com/ess-dmsc/ADPluginKafka).

**Comment by jwlodek** [comment]
Great thanks! I'll take a look
